version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t ansible_callback .
      - run: docker run -ti -v "$(pwd)/casts/:/tmp/output/" ansible_callback:latest
